name: Northman Management
favicon: null
layout_spectrum: 0.21205324307084084
typography_spectrum: 0.9449614172335714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0626618517562747
  lightness: 0.1142128985375166
  saturation: 0.014019423397257924
  rhythmicContrast: 0.9921481660567224
purpose: []
